spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/commence_api?createDatabaseIfNotExist=true
    username: root
    password: admin
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 86400
    refreshTokenExpiration: 604800
