spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/commence_api?createDatabaseIfNotExist=true
    username: root
    password: admin
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 864000
    refreshTokenExpiration: 604800

stripe:
  STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
  WEBHOOK_SECRET_KEY: ${WEBHOOK_SECRET_KEY}
# which might be the front end url or where it's hosted
websiteUrl: "https://test.com"
